include:
  # nice!nano
  - board: nice_nano_v2
    shield: cradio_left
  - board: nice_nano_v2
    shield: cradio_right

  # RP2040
  - board: sparkfun_pro_micro_rp2040
    shield: cradio_left
  - board: sparkfun_pro_micro_rp2040
    shield: cradio_right
